package by.antonov.webproject.controller;

public enum ResponseKey {
  RESP_FORM_RESULT_STATUS,
  RESP_FORM_RESULT_MESSAGE,

  RESP_REGISTRATION_EMAIL,
  RESP_REGISTRATION_PASSWORD,
  RESP_REGISTRATION_PASSWORD_CONFIRM,
  RESP_REGISTRATION_FIRST_NAME,
  RESP_REGISTRATION_LAST_NAME,
  RESP_REGISTRATION_PHONE,
  RESP_REGISTRATION_GROUP,

  RESP_USER_RESULT_LIST,

  RESP_ORDER_RESULT_LIST,
  RESP_ORDER,

  RESP_CURRENT_PAGE,
  RESP_MAX_PAGE
}
